### ISSUE TITLE
TypeError: adapter is not a function

### ISSUE THREAD

**Issue by cyri113** [Ankr-network/ankr.js#24]
I am using Supabase functions (powered by Deno). I am importing @ankr.com/ankr.js using an import map and skypack.dev as follows

```json
{
    "imports": {
        "server": "https://deno.land/std@0.168.0/http/server.ts",
        "lodash": "https://cdn.skypack.dev/lodash",
        "ethers": "https://cdn.skypack.dev/ethers@5.7.2",
        "http_status": "https://deno.land/std/http/http_status.ts",
        "@ankr.com/ankr.js": "https://cdn.skypack.dev/@ankr.com/ankr.js",
    }
}
```

I am making the following call:

```ts
import { AnkrProvider } from "@ankr.com/ankr.js"

const blockchain = [
    'eth',
    'bsc',
    'polygon',
    'avalanche'
]

const provider = new AnkrProvider()

export async function balances(walletAddress: string) {
    return await provider.getAccountBalance({
        blockchain,
        walletAddress
    })
}
```

Which results in the following error:

```bash
TypeError: adapter is not a function
    at dispatchRequest2 (https://cdn.skypack.dev/-/axios@v0.26.1-3c1TUCVdnljWzSKyoXbP/dist=es2019,mode=imports/optimized/axios.js:850:10)
    at Axios.request (https://cdn.skypack.dev/-/axios@v0.26.1-3c1TUCVdnljWzSKyoXbP/dist=es2019,mode=imports/optimized/axios.js:1057:15)
    at Axios.<computed> [as post] (https://cdn.skypack.dev/-/axios@v0.26.1-3c1TUCVdnljWzSKyoXbP/dist=es2019,mode=imports/optimized/axios.js:1081:17)
    at Function.wrap [as post] (https://cdn.skypack.dev/-/axios@v0.26.1-3c1TUCVdnljWzSKyoXbP/dist=es2019,mode=imports/optimized/axios.js:7:15)
    at AnkrProvider2.<anonymous> (https://cdn.skypack.dev/-/@ankr.com/ankr.js@v0.3.1-Ym5hVZaPt4QU3jCkJDJ0/dist=es2019,mode=imports/optimized/@ankr.com/ankrjs.js:131:48)
    at Generator.next (<anonymous>)
    at https://cdn.skypack.dev/-/@ankr.com/ankr.js@v0.3.1-Ym5hVZaPt4QU3jCkJDJ0/dist=es2019,mode=imports/optimized/@ankr.com/ankrjs.js:43:69
    at new Promise (<anonymous>)
    at __awaiter (https://cdn.skypack.dev/-/@ankr.com/ankr.js@v0.3.1-Ym5hVZaPt4QU3jCkJDJ0/dist=es2019,mode=imports/optimized/@ankr.com/ankrjs.js:25:12)
    at AnkrProvider2.send (https://cdn.skypack.dev/-/@ankr.com/ankr.js@v0.3.1-Ym5hVZaPt4QU3jCkJDJ0/dist=es2019,mode=imports/optimized/@ankr.com/ankrjs.js:129:14)
```

It looks to me like this is an issue with the config of the Axios library.

So far, I have tried to add the `regenerator-runtime` but it hasn't helped.

**Comment by ryeshrimp** [comment]
Same issue with cloudflare workers

**Comment by RedCuckoo** [comment]
Please, open a new one if the issue still exists
